version: '3.8'

services:
  web:
    build: .
    command: ["web"]
    volumes:
      - ./miniproject:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: ["celery"]
    volumes:
      - ./miniproject:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: ["celery-beat"]
    volumes:
      - ./miniproject:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
